<?php

// Directorio bancario SUDEBAN: https://sudeban.gob.ve/index.php/bancario/
return [
    '100% Banco',
    'Bancamiga',
    'Banco Activo',
    'Banco Agrícola de Venezuela',
    'Banco Digital de los Trabajadores',
    'Banco Caroní',
    'Bancoex',
    'Bandes',
    'Banfanb',
    'Bangente',
    'Banco de Venezuela',
    'Bancaribe',
    'Banco del Tesoro',
    'Banco Exterior',
    'Banco Internacional de Desarrollo',
    'Banco Nacional de Crédito',
    'Banavih',
    'Banco Plaza',
    'Banco Provincial',
    'Banco Sofitasa',
    'Bancrecer',
    'Banesco',
    'Banplus',
    'BFC Banco Fondo Común',
    'Del Sur',
    'Instituto Municipal de Crédito Popular',
    'Mercantil',
    'R4 Banco Microfinanciero',
    'Venezolano de Crédito',
    'N58 Banco Digital',
];
